apiVersion: v1
kind: Secret
metadata:
  name: aws-conf
  namespace: kube-system
data:
  aws_access_key_id: <access key id base64>
  aws_secret_access_key: <access key  base64>
  region: <region the ecr is located base64>
  output: <the command output base64 (i use json)>
  account_id: <your account id base64>
